### PR TITLE
Umarteau/fix-torch-iterator

### PR DESCRIPTION
**Pull request by umarteauowkin**

### CODE REVIEW

**Comment by umarteauowkin** [comment]
Bug fixed in the loss (the initialized zeros were not set on the right device in the case where GPus were used)

**Comment by umarteauowkin** [comment]
I spotted a bug in the DataLoader with memory code which occurs for torch = 1.13. I fixed it and designed a test which fails if the version is 1.12 and passes if the version is 1.13

**Review by jeandut — APPROVED** [review]
Thank you @umarteauowkin !

**Review by jeandut — COMMENTED** [review]
Could you just run black manually on all files you modified ? This is an issue with incompatibility between pre-commit hooks linting and CI linting.

**Pull request merged**
