### PR TITLE
Jean/fix log frequency

### PR DESCRIPTION
**Pull request by jeandut**
This PR decouples the check on the log frequency for loss and for weight histograms leading to more frequent logs for weights and solving #233.
This PR also get rid of unnecessary enumerate.

### CODE REVIEW

**Comment by jeandut** [comment]
@umarteauowkin is this what you think is needed ?

**Comment by umarteauowkin** [comment]
Yes seems good to me ! Another option would have been to log the histogram at the same frequency as the scalars, but I think this works fine as well.

**Comment by jeandut** [comment]
> Yes seems good to me ! Another option would have been to log the histogram at the same frequency as the scalars, but I think this works fine as well.

I don't think we want to much log of weights as it might take excruciating amount of times for big networks. Let's keep it as is and see if it passes the test of time.

**Comment by mandreux-owkin** [comment]
> I don't think we want to much log of weights as it might take excruciating amount of times for big networks. Let's keep it as is and see if it passes the test of time.

I fully agree with this comment 👍

**Review by maikia — APPROVED** [review]
LGTM

**Pull request merged**
